// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProfileSocialLinkRepository } from '../profile-social-link.repository';
import { ProfileSocialLinksRelationalRepository } from './repositories/profile-social-link.repository';
import { ProfileSocialLinkEntity } from './entities/profile-social-link.entity';

@Module({
  imports: [TypeOrmModule.forFeature([ProfileSocialLinkEntity])],
  providers: [
    {
      provide: ProfileSocialLinkRepository,
      useClass: ProfileSocialLinksRelationalRepository,
    },
  ],
  exports: [ProfileSocialLinkRepository],
})
export class RelationalProfileSocialLinkPersistenceModule {}
