// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { Profile } from '../../../../domain/profile.domain';
import { ProfileEntity } from '../entities/profile.entity';

export class ProfileMapper {
  static toDomain(entity: ProfileEntity): Profile {
    const domain = new Profile();
    domain.id = entity.id;
    domain.fullName = entity.fullName ?? null;
    domain.email = entity.email ?? null;
    domain.avatarUrl = entity.avatarUrl ?? null;
    domain.metadata = entity.metadata ?? null;
    domain.createdAt = entity.createdAt;
    domain.updatedAt = entity.updatedAt;
    domain.authId = entity.authId ?? null;
    domain.username = entity.username ?? null;
    domain.phone = entity.phone ?? null;
    domain.locale = entity.locale ?? null;
    domain.timezone = entity.timezone ?? null;
    domain.bio = entity.bio ?? null;
    domain.website = entity.website ?? null;
    domain.pronouns = entity.pronouns ?? null;
    return domain;
  }

  static toEntity(domain: Profile): ProfileEntity {
    const entity = new ProfileEntity();
    entity.id = domain.id;
    entity.fullName = domain.fullName ?? null;
    entity.email = domain.email ?? null;
    entity.avatarUrl = domain.avatarUrl ?? null;
    entity.metadata = domain.metadata ?? null;
    entity.createdAt = domain.createdAt;
    entity.updatedAt = domain.updatedAt;
    entity.authId = domain.authId ?? null;
    entity.username = domain.username ?? null;
    entity.phone = domain.phone ?? null;
    entity.locale = domain.locale ?? null;
    entity.timezone = domain.timezone ?? null;
    entity.bio = domain.bio ?? null;
    entity.website = domain.website ?? null;
    entity.pronouns = domain.pronouns ?? null;
    return entity;
  }
}
