// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

export { ProfileSocialLinksEntity as ProfileSocialLinkEntity } from '../../../../../../database/prisma/entities/profile-social-links.entity';
