// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { FindOptionsOrder, FindOptionsOrderValue, FindOptionsWhere, Repository } from 'typeorm';
import { DeepPartial } from '../../../../../../utils/types/deep-partial.type';
import { NullableType } from '../../../../../../utils/types/nullable.type';
import { IPaginationOptions } from '../../../../../../utils/types/pagination-options';
import { ProfileSocialLink } from '../../../../domain/profile-social-link.domain';
import { ProfileSocialLinkRepository } from '../../profile-social-link.repository';
import { ProfileSocialLinkMapper } from '../mappers/profile-social-link.mapper';
import { ProfileSocialLinkEntity } from '../entities/profile-social-link.entity';
import { FilterProfileSocialLinkDto, SortProfileSocialLinkDto } from '../../../../dto/query-profile-social-link.dto';

@Injectable()
export class ProfileSocialLinksRelationalRepository implements ProfileSocialLinkRepository {
  constructor(
    @InjectRepository(ProfileSocialLinkEntity)
    private readonly repository: Repository<ProfileSocialLinkEntity>,
  ) {}

  private readonly relations = ['profiles'];

  async create(data: Omit<ProfileSocialLink, 'id' | 'createdAt' | 'updatedAt'>): Promise<ProfileSocialLink> {
    const persistenceModel = ProfileSocialLinkMapper.toEntity(data as ProfileSocialLink);
    const entity = this.repository.create(persistenceModel);
    const saved = await this.repository.save(entity);
    return ProfileSocialLinkMapper.toDomain(saved);
  }

  async findManyWithPagination({
    filterOptions,
    sortOptions,
    paginationOptions,
  }: {
    filterOptions?: FilterProfileSocialLinkDto | null;
    sortOptions?: SortProfileSocialLinkDto[] | null;
    paginationOptions: IPaginationOptions;
  }): Promise<{ data: ProfileSocialLink[]; total: number }> {
    const page = paginationOptions?.page ?? 1;
    const limit = paginationOptions?.limit ?? 10;
    const where = this.buildWhere(filterOptions);
    const order = this.buildOrder(sortOptions);
    const [entities, total] = await this.repository.findAndCount({
      where,
      order,
      relations: this.relations.length ? this.relations : undefined,
      skip: (page - 1) * limit,
      take: limit,
    });
    return {
      data: entities.map((entity) => ProfileSocialLinkMapper.toDomain(entity)),
      total,
    };
  }

  async findById(id: ProfileSocialLink['id']): Promise<NullableType<ProfileSocialLink>> {
    const entity = await this.repository.findOne({ where: { id: id } as FindOptionsWhere<ProfileSocialLinkEntity>, relations: this.relations.length ? this.relations : undefined });
    return entity ? ProfileSocialLinkMapper.toDomain(entity) : null;
  }

  async update(id: ProfileSocialLink['id'], payload: DeepPartial<ProfileSocialLink>): Promise<ProfileSocialLink | null> {
    const entity = await this.repository.findOne({ where: { id: id } as FindOptionsWhere<ProfileSocialLinkEntity>, relations: this.relations.length ? this.relations : undefined });
    if (!entity) {
      return null;
    }
    const domain = ProfileSocialLinkMapper.toDomain(entity);
    const merged = { ...domain, ...payload } as ProfileSocialLink;
    const updated = this.repository.merge(entity, ProfileSocialLinkMapper.toEntity(merged));
    const saved = await this.repository.save(updated);
    return ProfileSocialLinkMapper.toDomain(saved);
  }

  async remove(id: ProfileSocialLink['id']): Promise<void> {
    await this.repository.delete({ id: id } as FindOptionsWhere<ProfileSocialLinkEntity>);
  }

  private buildWhere(filterOptions?: FilterProfileSocialLinkDto | null): FindOptionsWhere<ProfileSocialLinkEntity> | undefined {
    if (!filterOptions) {
      return undefined;
    }
    const where: Record<string, unknown> = {};
    if (filterOptions.id !== undefined) {
      where.id = filterOptions.id;
    }
    if (filterOptions.profileId !== undefined) {
      where.profileId = filterOptions.profileId;
    }
    if (filterOptions.kind !== undefined) {
      where.kind = filterOptions.kind;
    }
    if (filterOptions.url !== undefined) {
      where.url = filterOptions.url;
    }
    if (filterOptions.label !== undefined) {
      where.label = filterOptions.label;
    }
    if (filterOptions.createdAt !== undefined) {
      where.createdAt = filterOptions.createdAt;
    }
    if (filterOptions.updatedAt !== undefined) {
      where.updatedAt = filterOptions.updatedAt;
    }
    return Object.keys(where).length ? (where as FindOptionsWhere<ProfileSocialLinkEntity>) : undefined;
  }

  private buildOrder(sortOptions?: SortProfileSocialLinkDto[] | null): FindOptionsOrder<ProfileSocialLinkEntity> | undefined {
    if (!sortOptions || !sortOptions.length) {
      return undefined;
    }
    const order: FindOptionsOrder<ProfileSocialLinkEntity> = {};
    const orderRecord = order as Record<string, FindOptionsOrderValue>;
    sortOptions.forEach((sort) => {
      const direction = sort.order?.toUpperCase() === 'DESC' ? 'DESC' : 'ASC';
      orderRecord[sort.orderBy as string] = direction as FindOptionsOrderValue;
    });
    return order;
  }
}
