// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by generate-typeorm-entities.ts

import { Column, Entity, Index, PrimaryGeneratedColumn } from 'typeorm';
import { EntityRelationalHelper } from '../../../utils/relational-entity-helper';

@Entity({ name: 'profile' })
export class ProfileEntity extends EntityRelationalHelper {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({
  type: 'varchar',
  name: 'full_name',
  nullable: true
})
  fullName?: string | null;

  @Index('uq_profile_email', { unique: true })
  @Column({
  type: 'varchar',
  name: 'email',
  nullable: true
})
  email?: string | null;

  @Column({
  type: 'varchar',
  name: 'avatar_url',
  nullable: true
})
  avatarUrl?: string | null;
}
