// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { ProfileSocialLink } from '../../domain/profile-social-link.domain';
import { FilterProfileSocialLinkDto, SortProfileSocialLinkDto } from '../../dto/query-profile-social-link.dto';
import { DeepPartial } from '../../../../utils/types/deep-partial.type';
import { NullableType } from '../../../../utils/types/nullable.type';
import { IPaginationOptions } from '../../../../utils/types/pagination-options';

export abstract class ProfileSocialLinkRepository {
  abstract create(data: Omit<ProfileSocialLink, 'id' | 'createdAt' | 'updatedAt'>): Promise<ProfileSocialLink>;

  abstract findManyWithPagination({
    filterOptions,
    sortOptions,
    paginationOptions,
  }: {
    filterOptions?: FilterProfileSocialLinkDto | null;
    sortOptions?: SortProfileSocialLinkDto[] | null;
    paginationOptions: IPaginationOptions;
  }): Promise<{ data: ProfileSocialLink[]; total: number }>;

  abstract findById(id: ProfileSocialLink['id']): Promise<NullableType<ProfileSocialLink>>;
  abstract update(id: ProfileSocialLink['id'], payload: DeepPartial<ProfileSocialLink>): Promise<ProfileSocialLink | null>;
  abstract remove(id: ProfileSocialLink['id']): Promise<void>;
}
