// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { IsDate, IsNumber, IsOptional, IsString } from 'class-validator';
import { ProfileSocialLink } from '../domain/profile-social-link.domain';

export class FilterProfileSocialLinkDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  id?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  profileId?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  kind?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  url?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  label?: string | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsDate()
  @Type(() => Date)
  createdAt?: Date;

  @ApiPropertyOptional()
  @IsOptional()
  @IsDate()
  @Type(() => Date)
  updatedAt?: Date;
}

export class SortProfileSocialLinkDto {
  @ApiProperty()
  @Type(() => String)
  @IsString()
  orderBy!: keyof ProfileSocialLink;

  @ApiProperty()
  @IsString()
  order!: 'ASC' | 'DESC' | 'asc' | 'desc';
}

export class QueryProfileSocialLinkDto {
  @ApiPropertyOptional()
  @Type(() => Number)
  @IsNumber()
  @IsOptional()
  page?: number;

  @ApiPropertyOptional()
  @Type(() => Number)
  @IsNumber()
  @IsOptional()
  limit?: number;

  @ApiPropertyOptional({ type: () => FilterProfileSocialLinkDto })
  @IsOptional()
  @Type(() => FilterProfileSocialLinkDto)
  filters?: FilterProfileSocialLinkDto | null;

  @ApiPropertyOptional({ type: () => [SortProfileSocialLinkDto] })
  @IsOptional()
  @Type(() => SortProfileSocialLinkDto)
  sort?: SortProfileSocialLinkDto[] | null;
}
