// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { PartialType } from '@nestjs/swagger';
import { CreateProfileSocialLinkDto } from './create-profile-social-link.dto';

export class UpdateProfileSocialLinkDto extends PartialType(CreateProfileSocialLinkDto) {}
