// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ProfileRepository } from '../profile.repository';
import { ProfilesRelationalRepository } from './repositories/profile.repository';
import { ProfileEntity } from './entities/profile.entity';

@Module({
  imports: [TypeOrmModule.forFeature([ProfileEntity])],
  providers: [
    {
      provide: ProfileRepository,
      useClass: ProfilesRelationalRepository,
    },
  ],
  exports: [ProfileRepository],
})
export class RelationalProfilePersistenceModule {}
