// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { PartialType } from '@nestjs/swagger';
import { CreateProfileDto } from './create-profile.dto';

export class UpdateProfileDto extends PartialType(CreateProfileDto) {}
