// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { FindOptionsOrder, FindOptionsOrderValue, FindOptionsWhere, Repository } from 'typeorm';
import { DeepPartial } from '../../../../../../utils/types/deep-partial.type';
import { NullableType } from '../../../../../../utils/types/nullable.type';
import { IPaginationOptions } from '../../../../../../utils/types/pagination-options';
import { Profile } from '../../../../domain/profile.domain';
import { ProfileRepository } from '../../profile.repository';
import { ProfileMapper } from '../mappers/profile.mapper';
import { ProfileEntity } from '../entities/profile.entity';
import { FilterProfileDto, SortProfileDto } from '../../../../dto/query-profile.dto';

@Injectable()
export class ProfilesRelationalRepository implements ProfileRepository {
  constructor(
    @InjectRepository(ProfileEntity)
    private readonly repository: Repository<ProfileEntity>,
  ) {}

  private readonly relations = [];

  async create(data: Omit<Profile, 'id' | 'createdAt' | 'updatedAt'>): Promise<Profile> {
    const persistenceModel = ProfileMapper.toEntity(data as Profile);
    const entity = this.repository.create(persistenceModel);
    const saved = await this.repository.save(entity);
    return ProfileMapper.toDomain(saved);
  }

  async findManyWithPagination({
    filterOptions,
    sortOptions,
    paginationOptions,
  }: {
    filterOptions?: FilterProfileDto | null;
    sortOptions?: SortProfileDto[] | null;
    paginationOptions: IPaginationOptions;
  }): Promise<{ data: Profile[]; total: number }> {
    const page = paginationOptions?.page ?? 1;
    const limit = paginationOptions?.limit ?? 10;
    const where = this.buildWhere(filterOptions);
    const order = this.buildOrder(sortOptions);
    const [entities, total] = await this.repository.findAndCount({
      where,
      order,
      relations: this.relations.length ? this.relations : undefined,
      skip: (page - 1) * limit,
      take: limit,
    });
    return {
      data: entities.map((entity) => ProfileMapper.toDomain(entity)),
      total,
    };
  }

  async findById(id: Profile['id']): Promise<NullableType<Profile>> {
    const entity = await this.repository.findOne({ where: { id: id } as FindOptionsWhere<ProfileEntity>, relations: this.relations.length ? this.relations : undefined });
    return entity ? ProfileMapper.toDomain(entity) : null;
  }

  async update(id: Profile['id'], payload: DeepPartial<Profile>): Promise<Profile | null> {
    const entity = await this.repository.findOne({ where: { id: id } as FindOptionsWhere<ProfileEntity>, relations: this.relations.length ? this.relations : undefined });
    if (!entity) {
      return null;
    }
    const domain = ProfileMapper.toDomain(entity);
    const merged = { ...domain, ...payload } as Profile;
    const updated = this.repository.merge(entity, ProfileMapper.toEntity(merged));
    const saved = await this.repository.save(updated);
    return ProfileMapper.toDomain(saved);
  }

  async remove(id: Profile['id']): Promise<void> {
    await this.repository.delete({ id: id } as FindOptionsWhere<ProfileEntity>);
  }

  private buildWhere(filterOptions?: FilterProfileDto | null): FindOptionsWhere<ProfileEntity> | undefined {
    if (!filterOptions) {
      return undefined;
    }
    const where: Record<string, unknown> = {};
    if (filterOptions.id !== undefined) {
      where.id = filterOptions.id;
    }
    if (filterOptions.fullName !== undefined) {
      where.fullName = filterOptions.fullName;
    }
    if (filterOptions.email !== undefined) {
      where.email = filterOptions.email;
    }
    if (filterOptions.avatarUrl !== undefined) {
      where.avatarUrl = filterOptions.avatarUrl;
    }
    if (filterOptions.metadata !== undefined) {
      where.metadata = filterOptions.metadata;
    }
    if (filterOptions.createdAt !== undefined) {
      where.createdAt = filterOptions.createdAt;
    }
    if (filterOptions.updatedAt !== undefined) {
      where.updatedAt = filterOptions.updatedAt;
    }
    if (filterOptions.authId !== undefined) {
      where.authId = filterOptions.authId;
    }
    if (filterOptions.username !== undefined) {
      where.username = filterOptions.username;
    }
    if (filterOptions.phone !== undefined) {
      where.phone = filterOptions.phone;
    }
    if (filterOptions.locale !== undefined) {
      where.locale = filterOptions.locale;
    }
    if (filterOptions.timezone !== undefined) {
      where.timezone = filterOptions.timezone;
    }
    if (filterOptions.bio !== undefined) {
      where.bio = filterOptions.bio;
    }
    if (filterOptions.website !== undefined) {
      where.website = filterOptions.website;
    }
    if (filterOptions.pronouns !== undefined) {
      where.pronouns = filterOptions.pronouns;
    }
    return Object.keys(where).length ? (where as FindOptionsWhere<ProfileEntity>) : undefined;
  }

  private buildOrder(sortOptions?: SortProfileDto[] | null): FindOptionsOrder<ProfileEntity> | undefined {
    if (!sortOptions || !sortOptions.length) {
      return undefined;
    }
    const order: FindOptionsOrder<ProfileEntity> = {};
    const orderRecord = order as Record<string, FindOptionsOrderValue>;
    sortOptions.forEach((sort) => {
      const direction = sort.order?.toUpperCase() === 'DESC' ? 'DESC' : 'ASC';
      orderRecord[sort.orderBy as string] = direction as FindOptionsOrderValue;
    });
    return order;
  }
}
