// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { Profile } from '../../domain/profile.domain';
import { FilterProfileDto, SortProfileDto } from '../../dto/query-profile.dto';
import { DeepPartial } from '../../../../utils/types/deep-partial.type';
import { NullableType } from '../../../../utils/types/nullable.type';
import { IPaginationOptions } from '../../../../utils/types/pagination-options';

export abstract class ProfileRepository {
  abstract create(data: Omit<Profile, 'id' | 'createdAt' | 'updatedAt'>): Promise<Profile>;

  abstract findManyWithPagination({
    filterOptions,
    sortOptions,
    paginationOptions,
  }: {
    filterOptions?: FilterProfileDto | null;
    sortOptions?: SortProfileDto[] | null;
    paginationOptions: IPaginationOptions;
  }): Promise<{ data: Profile[]; total: number }>;

  abstract findById(id: Profile['id']): Promise<NullableType<Profile>>;
  abstract update(id: Profile['id'], payload: DeepPartial<Profile>): Promise<Profile | null>;
  abstract remove(id: Profile['id']): Promise<void>;
}
