// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

export { ProfileEntity as ProfileEntity } from '../../../../../../database/prisma/entities/profile.entity';
