// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Profile } from '../../profile/domain/profile.domain';

export class ProfileSocialLink {
  @ApiProperty()
  id!: string;

  @ApiProperty()
  profileId!: string;

  @ApiProperty()
  kind!: string;

  @ApiProperty()
  url!: string;

  @ApiPropertyOptional()
  label?: string | null;

  @ApiProperty()
  createdAt!: Date;

  @ApiProperty()
  updatedAt!: Date;

  @ApiProperty({ type: () => Profile })
  profiles!: Profile | null;
}
