// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tools/scripts/generate-hexagonal-resources.ts

import { ProfileSocialLink } from '../../../../domain/profile-social-link.domain';
import { ProfileSocialLinkEntity } from '../entities/profile-social-link.entity';
import { ProfileMapper } from '../../../../../profile/infrastructure/persistence/relational/mappers/profile.mapper';

export class ProfileSocialLinkMapper {
  static toDomain(entity: ProfileSocialLinkEntity): ProfileSocialLink {
    const domain = new ProfileSocialLink();
    domain.id = entity.id;
    domain.profileId = entity.profileId;
    domain.kind = entity.kind;
    domain.url = entity.url;
    domain.label = entity.label ?? null;
    domain.createdAt = entity.createdAt;
    domain.updatedAt = entity.updatedAt;
    domain.profiles = entity.profiles ? ProfileMapper.toDomain(entity.profiles) : null;
    return domain;
  }

  static toEntity(domain: ProfileSocialLink): ProfileSocialLinkEntity {
    const entity = new ProfileSocialLinkEntity();
    entity.id = domain.id;
    entity.profileId = domain.profileId;
    entity.kind = domain.kind;
    entity.url = domain.url;
    entity.label = domain.label ?? null;
    entity.createdAt = domain.createdAt;
    entity.updatedAt = domain.updatedAt;
    if (domain.profiles) {
      entity.profiles = ProfileMapper.toEntity(domain.profiles);
    }
    return entity;
  }
}
